[default]
default_peft_path = ""
working_dir = "flowertune-eval"
batch_size = 16
run_name = "fl"

[general_nlp]
working_dir = "flowertune-eval-general-nlp"
batch_size = 16
script = "eval.py"
category = "stem,social_sciences,humanities"

[finance]
working_dir = "flowertune-eval-finance"
batch_size = 16
script = "eval.py"
datasets = "fpb,fiqa,tfns"

[medical]
working_dir = "flowertune-eval-medical"
batch_size = 8
script = "eval.py"
datasets = "pubmedqa,medmcqa,medqa,careqa"

[code]
working_dir = "flowertune-eval-code"
batch_size = 4
script = "eval.py"
tasks = [ "humaneval", "mbpp", "multiple-js", "multiple-cpp",]
max_length_generation = 1024
allow_code_execution = true
save_generations = true
save_references = true
use_auth_token = true

[models."mistralai/Ministral-8B-Instruct-2410"]
peft_path = ""
trust_remote_code = true
quantization = 4

[models."Qwen/Qwen2.5-7B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/medical_Qwen_Qwen2.5-7B-Instruct_20250404_141928/peft_10"
trust_remote_code = true
quantization = 4

[models."meta-llama/Llama-3.1-8B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/medical_meta-llama_Llama-3.1-8B-Instruct_20250404_142552/peft_10"
trust_remote_code = false
quantization = 4

[models."mistralai/Mistral-7B-Instruct-v0.3"]
peft_path = "/home/st/flwr-nlp/results/medical_mistralai_Mistral-7B-Instruct-v0.3_20250404_142913/peft_10"
trust_remote_code = false
quantization = 4

[models."mistralai/Mistral-7B-v0.3"]
peft_path = ""
trust_remote_code = false
quantization = 4

[models."Qwen/Qwen2.5-1.5B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/medical_Qwen_Qwen2.5-1.5B-Instruct_20250404_141619/peft_10"
trust_remote_code = false
quantization = 4

[models."meta-llama/Llama-3.2-1B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/medical_meta-llama_Llama-3.2-1B-Instruct_20250404_142248/peft_10"
trust_remote_code = false
quantization = 4

[models."TinyLlama/TinyLlama-1.1B-Chat-v1.0"]
peft_path = ""
trust_remote_code = false
quantization = 4

[models."google/gemma-3-1b-it"]
peft_path = ""
trust_remote_code = false
quantization = 4

[models."facebook/MobileLLM-1B"]
peft_path = ""
trust_remote_code = false
quantization = 4

[models."mlx-community/Llama-3.2-1B-Instruct-4bit"]
peft_path = ""
trust_remote_code = false
quantization = 4

[models."deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"]
peft_path = "/home/st/flwr-nlp/results/medical_deepseek-ai_DeepSeek-R1-Distill-Qwen-1.5B_20250404_143326/peft_10"
trust_remote_code = false
quantization = 4

[tasks.general-nlp.models."mistralai/Mistral-7B-v0.3"]
peft_path = "/home/st/flwr-nlp/results/general-nlp_mistralai_Mistral-7B-v0.3_20250401_100230/peft_10"

[tasks.general-nlp.models."meta-llama/Llama-3.2-1B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/general-nlp_meta-llama_Llama-3.2-1B-Instruct_20250401_103045/peft_10"

[tasks.finance.models."meta-llama/Llama-3.2-1B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/finance_meta-llama_Llama-3.2-1B-Instruct_20250404_005805/peft_10"

[tasks.finance.models."Qwen/Qwen2.5-1.5B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/finance_Qwen_Qwen2.5-1.5B-Instruct_20250404_001552/peft_10"

[tasks.finance.models."Qwen/Qwen2.5-7B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/finance_Qwen_Qwen2.5-7B-Instruct_20250404_002657/peft_10"

[tasks.finance.models."meta-llama/Llama-3.1-8B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/finance_meta-llama_Llama-3.1-8B-Instruct_20250404_010837/peft_10"

[tasks.finance.models."mistralai/Mistral-7B-Instruct-v0.3"]
peft_path = "/home/st/flwr-nlp/results/finance_mistralai_Mistral-7B-Instruct-v0.3_20250404_014217/peft_10"

[tasks.finance.models."deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"]
peft_path = "/home/st/flwr-nlp/results/finance_deepseek-ai_DeepSeek-R1-Distill-Qwen-1.5B_20250404_021846/peft_10"

[tasks.medical.models."meta-llama/Llama-3.2-1B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/medical_meta-llama_Llama-3.2-1B-Instruct_20250404_142248/peft_10"

[tasks.medical.models."Qwen/Qwen2.5-1.5B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/medical_Qwen_Qwen2.5-1.5B-Instruct_20250404_141619/peft_10"

[tasks.medical.models."Qwen/Qwen2.5-7B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/medical_Qwen_Qwen2.5-7B-Instruct_20250404_141928/peft_10"

[tasks.medical.models."meta-llama/Llama-3.1-8B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/medical_meta-llama_Llama-3.1-8B-Instruct_20250404_142552/peft_10"

[tasks.medical.models."mistralai/Mistral-7B-Instruct-v0.3"]
peft_path = "/home/st/flwr-nlp/results/medical_mistralai_Mistral-7B-Instruct-v0.3_20250404_142913/peft_10"

[tasks.medical.models."deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"]
peft_path = "/home/st/flwr-nlp/results/medical_deepseek-ai_DeepSeek-R1-Distill-Qwen-1.5B_20250404_143326/peft_10"

[tasks.code.models."meta-llama/Llama-3.2-1B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/code_meta-llama_Llama-3.2-1B-Instruct_20250403_150122/peft_10"

[tasks.code.models."Qwen/Qwen2.5-1.5B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/code_Qwen_Qwen2.5-1.5B-Instruct_20250403_163418/peft_10"
