[default]
run_name = "fl"
batch_size = 16
category = "stem,social_sciences,humanities"
working_dir = "flowertune-eval-general-nlp"
default_peft_path = "/home/st/flwr-nlp/results/2025-03-25_15-28-46/peft_10"

[general_nlp]
batch_size = 16
working_dir = "flowertune-eval-general-nlp"
category = "stem,social_sciences,humanities"
script = "eval.py"

[finance]
batch_size = 32
working_dir = "flowertune-eval-finance"
datasets = "fpb,fiqa,tfns"
script = "eval.py"

[medical]
batch_size = 16
working_dir = "flowertune-eval-medical"
datasets = "pubmedqa,medmcqa,medqa,careqa"
script = "eval.py"

[code]
batch_size = 4
working_dir = "flowertune-eval-code"
script = "main.py"
max_length_generation = 1024
tasks = [ "humaneval", "mbpp", "multiple-js", "multiple-cpp",]
allow_code_execution = true
save_generations = true
save_references = true
use_auth_token = true

[models."Qwen/Qwen2.5-7B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/2025-03-31_13-17-23/peft_10"
trust_remote_code = false
quantization = 4

[models."meta-llama/Llama-3.1-8B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/2025-03-31_04-40-09/peft_10"
trust_remote_code = false
quantization = 4

[models."mistralai/Mistral-7B-v0.3"]
peft_path = "/home/st/flwr-nlp/results/2025-03-25_15-28-46/peft_10"
trust_remote_code = false
quantization = 4

[models."mistralai/Mistral-7B-Instruct-v0.3"]
peft_path = "/home/st/flwr-nlp/results/2025-03-31_05-14-16/peft_10"
trust_remote_code = false
quantization = 4

[models."mistralai/Ministral-8B-Instruct-2410"]
peft_path = "/home/st/flwr-nlp/results/2025-03-31_14-22-50/peft_5"
trust_remote_code = false
quantization = 4

[models."Qwen/Qwen2.5-1.5B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/2025-03-31_13-55-00/peft_10"
trust_remote_code = false
quantization = 4

[models."meta-llama/Llama-3.2-1B-Instruct"]
peft_path = "/home/st/flwr-nlp/results/2025-03-31_04-31-46/peft_10"
trust_remote_code = false
quantization = 4

[models."TinyLlama/TinyLlama-1.1B-Chat-v1.0"]
peft_path = "/home/st/flwr-nlp/results/2025-03-31_11-22-03/peft_10"
trust_remote_code = false
quantization = 4

[models."google/gemma-3-1b-it"]
peft_path = "/home/st/flwr-nlp/results/2025-03-25_15-28-46/peft_10"
trust_remote_code = false
quantization = 4

[models."facebook/MobileLLM-1B"]
peft_path = "/home/st/flwr-nlp/results/2025-03-25_15-28-46/peft_10"
trust_remote_code = false
quantization = 4

[models."mlx-community/Llama-3.2-1B-Instruct-4bit"]
peft_path = "/home/st/flwr-nlp/results/2025-03-27_01-56-41/peft_10"
trust_remote_code = false
quantization = 4

[models."deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"]
peft_path = "/home/st/flwr-nlp/results/2025-03-31_11-30-26/peft_10"
trust_remote_code = false
quantization = 4
