# 模型下载配置文件
# 可以在这里列出需要下载的所有模型

models:
  - name: "Qwen/Qwen2.5-7B-Instruct"
  - name: "meta-llama/Llama-3.1-8B-Instruct"
  - name: "mistralai/Mistral-7B-Instruct-v0.3"
  - name: "mistralai/Ministral-8B-Instruct-2410"



  # - name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
  # - name: "meta-llama/Llama-3.2-1B-Instruct"
  # - name: "Qwen/Qwen2.5-1.5B-Instruct"
  # - name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  # - name: "google/gemma-3-1b-it"
  # - name: "facebook/MobileLLM-1B"
  # - name: "mlx-community/Llama-3.2-1B-Instruct-4bit"

  
  # 可以添加更多模型，例如：
  # - name: "apple/OpenELM-1_1B-Instruct"
  # - name: "mistralai/Mistral-7B-v0.1"
  #   quantization: 8
  
  # - name: "meta-llama/Llama-2-7b-hf"
  #   quantization: 4 